#!/bin/bash
# scripts/new-provider.sh — Scaffold a plug-and-play providers/<id>/ package.
#
# Usage:
#   bash scripts/new-provider.sh myplatform
#   bash scripts/new-provider.sh myplatform --with-hooks --with-usage
#
# After scaffold:
#   1. Edit providers/<id>/__init__.py (prefixes, presets, labels)
#   2. Optional hooks.py / usage.py
#   3. uv run python lib/provider_catalog.py list
#   4. Add [[backends]] rows in relay.toml (see docs/PROVIDERS.md)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ID="${1:-}"
shift || true
WITH_HOOKS=0
WITH_USAGE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --with-hooks) WITH_HOOKS=1; shift ;;
        --with-usage) WITH_USAGE=1; shift ;;
        -h | --help)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            printf 'unknown arg: %s\n' "$1" >&2
            exit 2
            ;;
    esac
done

if [[ -z "$ID" || ! "$ID" =~ ^[a-z][a-z0-9_]*$ ]]; then
    printf 'usage: new-provider.sh <id> [--with-hooks] [--with-usage]\n' >&2
    exit 2
fi

DIR="$ROOT/providers/$ID"
if [[ -e "$DIR" ]]; then
    printf 'providers/%s already exists\n' "$ID" >&2
    exit 1
fi
mkdir -p "$DIR"

TITLE="$(printf '%s' "$ID" | python3 -c 'import sys; print(sys.stdin.read().strip().replace("_"," ").title())')"

cat >"$DIR/__init__.py" <<EOF
"""${TITLE} provider — generated by scripts/new-provider.sh.

Plug-and-play: this package is auto-discovered via providers.discover_and_import().
"""

from __future__ import annotations

from providers.base import DeliveryPreset, Provider, register
EOF

if (( WITH_USAGE == 1 )); then
    cat >>"$DIR/__init__.py" <<EOF
from providers.${ID}.usage import collect_usage, default_usage_dir
EOF
fi

if (( WITH_HOOKS == 1 )); then
    cat >>"$DIR/__init__.py" <<EOF
from providers.${ID}.hooks import EVENTS, format_hook, normalize_event
EOF
fi

cat >>"$DIR/__init__.py" <<EOF

_PRESETS = (
    DeliveryPreset(
        backend_type="${ID}",
        delivery="cmd",
        model="",
        prefixes=("@${ID}", "/${ID}", "${ID}:"),
        tag="${ID}",
        cmd=(
            "bash",
            "-lc",
            'printf "echo from ${ID}: %s\\\\n" "\$RELAY_TEXT" '
            '| RELAY_BACKEND=${ID} "\${BRIDGE_DIR:-\$HOME/.claude/telegram-bridge}/relay-notify.sh" --raw',
        ),
        notes="Replace cmd with your CLI/HTTP inject. See docs/PROVIDERS.md.",
    ),
)

PROVIDER = register(
    Provider(
        id="${ID}",
        display_name="${TITLE}",
        config_namespace="${ID}",
        backend_id="${ID}",
EOF

if (( WITH_HOOKS == 1 )); then
    cat >>"$DIR/__init__.py" <<EOF
        hook_events=list(EVENTS),
        normalize_event=normalize_event,
        format_hook=format_hook,
EOF
else
    cat >>"$DIR/__init__.py" <<EOF
        hook_events=[],
EOF
fi

if (( WITH_USAGE == 1 )); then
    cat >>"$DIR/__init__.py" <<EOF
        usage_source="${ID}",
        usage_default_dir=default_usage_dir(),
        usage_collect=collect_usage,
EOF
else
    cat >>"$DIR/__init__.py" <<EOF
        usage_source=None,
EOF
fi

cat >>"$DIR/__init__.py" <<EOF
        model_prefixes=(),
        provider_label="${ID}",
        backend_types=("${ID}",),
        delivery_presets=_PRESETS,
        description="${TITLE} plug-and-play provider (scaffold).",
    )
)
EOF

if (( WITH_USAGE == 1 )); then
    cat >"$DIR/usage.py" <<EOF
"""${TITLE} usage collector stub."""

from __future__ import annotations

from pathlib import Path
from typing import Any


class NoLocalUsageLogs(Exception):
    pass


def default_usage_dir() -> str:
    return str(Path.home() / ".${ID}")


def collect_usage(base: Path) -> list[Any]:
    _ = base
    raise NoLocalUsageLogs("no local usage logs for ${ID} yet")
EOF
fi

if (( WITH_HOOKS == 1 )); then
    cat >"$DIR/hooks.py" <<EOF
"""${TITLE} hook formatting (scaffold)."""

from __future__ import annotations

from typing import Any

from providers.base import HookEvent

EVENTS = (
    HookEvent("Stop", default_enabled=True, default_prefix="🏁", description="Turn finished"),
    HookEvent("Notification", default_enabled=True, default_prefix="🔔"),
)


def normalize_event(raw: str) -> str:
    r = (raw or "").strip()
    if not r:
        return "unknown"
    # Map snake_case / aliases → PascalCase catalog names as needed.
    for e in EVENTS:
        if e.name.lower() == r.lower() or e.name == r:
            return e.name
    return r


def format_hook(payload: dict[str, Any], event: str, opts: dict[str, str]) -> str:
    prefix = opts.get("prefix") or "ℹ️"
    msg = (
        payload.get("message")
        or payload.get("last_assistant_message")
        or payload.get("text")
        or event
    )
    text = str(msg).replace("\\n", " ").strip()
    if len(text) > 400:
        text = text[:397] + "…"
    return f"{prefix} {text}"
EOF
fi

printf 'Created providers/%s/\n' "$ID"
printf 'Next:\n'
printf '  uv run python lib/provider_catalog.py list | head\n'
printf '  uv run python lib/provider_catalog.py presets %s\n' "$ID"
printf '  # add [backends.%s] from the preset into relay.toml\n' "$ID"
